[package]
name = "win_opt"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.4", features = ["derive"] }
colored = "2.0"
directories = "5.0"
indicatif = "0.17"
sysinfo = "0.30"
dialoguer = "0.11"